### ISSUE TITLE
Fatal error on doctrine:generate:entities command

### ISSUE THREAD

**Issue by codedmonkey** [symfony-cmf/RoutingBundle#344] opened 2016-03-15 22:46 UTC
When trying to run the `doctrine:generate:entities` command after enabling the RoutingBundle I get the following error message:

    PHP Fatal error:  Call to a member function getName() on a non-object in /{path}/vendor/symfony-cmf/routing-bundle/Doctrine/RouteConditionMetadataListener.php on line 52

What I've been able to figure out is that when executing the `loadClassMetadata` event in this listener, the listener is trying to establish a ReflectionClass to see if it's not an instance of a `Route` object but is unable to do so, generating a fatal error. I tried looking into the `loadClassMetadata` event but the information I could find about it was very sparse, so I'm not sure what exactly needs to be changed here. When the dynamic router is disabled in config.yml the command runs fine.

My composer is set up to run Symfony 2.7 and I'm running the master branch of the RoutingBundle.

I was able to fix the problem by adding an additional check to the line:

    if ('object' == gettype($meta->getReflectionClass()) && $meta->getReflectionClass()->getName() !== 'Symfony\Component\Routing\Route') {

but this probably isn't adhering to the coding standards =P and like I said, I'm not sure what the `loadMetadataClass` event is trying to accomplish, that's why I'm posting it here.

Full error message:

    Tims-MacBook:wiki timgoudriaan$ php app/console doctrine:generate:entities CodedMonkeyWikiBundle
    Generating entities for bundle "CodedMonkeyWikiBundle"
    PHP Fatal error:  Call to a member function getName() on a non-object in /{path}/vendor/symfony-cmf/routing-bundle/Doctrine/RouteConditionMetadataListener.php on line 52
    PHP Stack trace:
    PHP   1. {main}() /{path}/app/console:0
    PHP   2. Symfony\Component\Console\Application->run() /{path}/app/console:27
    PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
    PHP   4. Symfony\Component\Console\Application->doRun() /{path}/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:90
    PHP   5. Symfony\Component\Console\Application->doRunCommand() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
    PHP   6. Symfony\Component\Console\Command\Command->run() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:849
    PHP   7. Doctrine\Bundle\DoctrineBundle\Command\GenerateEntitiesDoctrineCommand->execute() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
    PHP   8. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getBundleMetadata() /{path}/vendor/doctrine/doctrine-bundle/Command/GenerateEntitiesDoctrineCommand.php:96
    PHP   9. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getMetadataForNamespace() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:54
    PHP  10. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getAllMetadata() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:172
    PHP  11. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:209
    PHP  12. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:115
    PHP  13. Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
    PHP  14. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() /{path}/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
    PHP  15. Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
    PHP  16. Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() /{path}/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:248
    PHP  17. Symfony\Cmf\Bundle\RoutingBundle\Doctrine\RouteConditionMetadataListener->loadClassMetadata() /{path}/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:63
    
    Fatal error: Call to a member function getName() on a non-object in /{path}/vendor/symfony-cmf/routing-bundle/Doctrine/RouteConditionMetadataListener.php on line 52
    
    Call Stack:
        0.0004     230112   1. {main}() /{path}/app/console:0
        0.0457    3374216   2. Symfony\Component\Console\Application->run() /{path}/app/console:27
        0.0513    3597088   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
        1.3571   18294200   4. Symfony\Component\Console\Application->doRun() /{path}/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:90
        1.3574   18295168   5. Symfony\Component\Console\Application->doRunCommand() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
        1.3668   18558160   6. Symfony\Component\Console\Command\Command->run() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:849
        1.3674   18564056   7. Doctrine\Bundle\DoctrineBundle\Command\GenerateEntitiesDoctrineCommand->execute() /{path}/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
        1.3840   18738280   8. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getBundleMetadata() /{path}/vendor/doctrine/doctrine-bundle/Command/GenerateEntitiesDoctrineCommand.php:96
        1.3841   18738480   9. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getMetadataForNamespace() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:54
        1.3841   18738704  10. Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getAllMetadata() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:172
        1.3850   18759816  11. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() /{path}/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:209
        1.4650   18977280  12. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:115
        1.4651   18977376  13. Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
        1.4651   18977376  14. Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() /{path}/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
        1.4660   18996536  15. Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() /{path}/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
        1.4676   19009304  16. Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() /{path}/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:248
        1.4676   19009456  17. Symfony\Cmf\Bundle\RoutingBundle\Doctrine\RouteConditionMetadataListener->loadClassMetadata() /{path}/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:63

**Comment by WouterJ** [comment] 2016-03-19 11:39
Hi @codedmonkey!

I can confirm you found a bug in the class and I have good news for you: Your fix is 99% correct. You've correctly identified the error, but it's more common to check if `getReflectionClass()` returns `null` instead of checking if returns an object.

It would be great if you can contribute the fix, e.g. by doing:
```diff
+ $refl = $meta->getReflectionClass();
+ if (null !== $refl && $refl->getName() !== 'Symfony\Component\Routing\Route') {
- if ($meta->getReflectionClass() !== 'Symfony\Component\Routing\Route') {
     return;
 }
```
This way you'll get the credits.

A little side information to give you some tip: While this is indeed a bug, you finding it is caused by a bit of misuse of the `doctrine:generate:entities` command (but that's not your fault, it's because the Symfony docs incorrectly recommeds using it). This commands should be used to generate entities from mapping information (e.g. when you only write the mapping file and don't have the class yet, because you [reverse-engineered from using native PDO](http://symfony.com/doc/current/cookbook/doctrine/reverse_engineering.html) or the like).

If you're using Doctrine from the start to create your entities, it's often better to write the getters/setters yourself. This avoids getting unnessary setters or getters (e.g. you should wonder if you want to make people able to change the id after creating the the entity) and if you use an IDE like PHPstorm, generating this bootstrap code isn't hard :)

**Comment by WouterJ** [comment] 2016-03-19 11:40
Oh, I'm sorry, there already is a PR fixing this bug: https://github.com/symfony-cmf/RoutingBundle/pull/340 Still, many thanks for reporing it!

**Comment by WouterJ** [comment] 2016-03-19 11:43
Closing as I just merged https://github.com/symfony-cmf/RoutingBundle/pull/340

**Closed by WouterJ** 2016-03-19 11:43 UTC
Labels: bug, orm

**Comment by codedmonkey** [comment] 2016-03-19 13:55
Thanks for the advice @WouterJ, I really appreciate it.

I was in the process of making a pull request but I'm glad it's being resolved. I know I'm abusing the Symfony command and was actually just looking to purchase PhpStorm for myself so I will look into that.
