### ISSUE TITLE
symfony 2.8 support

### ISSUE THREAD

**Issue by killerwolf** [symfony-cmf/RoutingBundle#324] opened 2015-12-22 21:37 UTC
add support for symfony2.8

**Comment by dbu** [comment] 2015-12-22 21:53
we already build with symfony 2.8: https://travis-ci.org/symfony-cmf/RoutingBundle/jobs/98222678 but allow failures.

there seems to be some setup issue of some sort - maybe between this repo and testing?

**Comment by killerwolf** [comment] 2015-12-22 23:28
WIP here https://github.com/symfony-cmf/RoutingBundle/pull/325

**Comment by WouterJ** [comment] 2015-12-23 12:51
We should already have 2.8 support, as there are no breaking changes between 2.7 and 2.8.

What is it that is not working while installing this bundle with Symfony 2.8?

The test @dbu referenced was one from a PR, caused by wrong dependencies. See https://travis-ci.org/symfony-cmf/RoutingBundle/jobs/98197708 for a successful test against Symfony 2.8.

**Comment by killerwolf** [comment] 2015-12-23 13:45
you're right about 2.8 support, we pushed RoutingBundle on production with a sf2.8 project.

So what's the next step toward sf3? deprecation warnings fix ?

**Comment by WouterJ** [comment] 2015-12-23 13:57
For now, I think the next step is to release RoutingBundle 1.3 with the current feature set.

After the release, bump master to be 2.0 and require PHP >5.5.9 + Symfony 2.8. If something works on Symfony 3.0, it works on Symfony 2.8 as well. We are quite a small team and simply don't have the resources to use big BC layers in the code.

**Comment by dbu** [comment] 2015-12-23 17:59
@wouterj look at #325, the fuctional test setup is broken. might be some
other dependency, did not find time to investigate. agree on the plan: tag
1.3 asap, ignoring deprecations if needed, then wrap up the pr for 3.0 and
only suppprt 2.8 and 3 afterwards

**Comment by WouterJ** [comment] 2015-12-23 18:03
@dbu that's exactly for the same reason I explained in the Symfony 3 PR: https://github.com/symfony-cmf/RoutingBundle/pull/323#issuecomment-166605477 As the PR allows SonataDoctrinePHPCRBundle 2.0 to be installed, TreeBrowserBundle 2.0 is installed in the tests. This bundle has no routes, but the Testing component still predefines the config for TreeBrowserBundle 1.x, which has routes.

**Comment by dbu** [comment] 2015-12-29 09:30
fixed in #326

**Closed by dbu** 2015-12-29 09:30 UTC

**Comment by killerwolf** [comment] 2015-12-29 10:12
well done :)
